
#inserting the hand written (a) files
data_a1 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/a/a.pgm", skip = 3, sep = ",")
data_a2 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/a/a2.pgm", skip = 3, sep = ",")
data_a3 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/a/a3.pgm", skip = 3, sep = ",")
data_a4 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/a/a4.pgm", skip = 3, sep = ",")
data_a5 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/a/a5.pgm", skip = 3, sep = ",")
data_a6 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/a/a6.pgm", skip = 3, sep = ",")
data_a7 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/a/a7.pgm", skip = 3, sep = ",")
data_a8 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/a/a8.pgm", skip = 3, sep = ",")

#inserting all the (b) files
data_b1 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/b/b.pgm", skip = 3, sep = ",")
data_b2 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/b/b2.pgm", skip = 3, sep = ",")
data_b3 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/b/b3.pgm", skip = 3, sep = ",")
data_b4 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/b/b4.pgm", skip = 3, sep = ",")
data_b5 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/b/b5.pgm", skip = 3, sep = ",")
data_b6 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/b/b6.pgm", skip = 3, sep = ",")
data_b7 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/b/b7.pgm", skip = 3, sep = ",")
data_b8 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/b/b8.pgm", skip = 3, sep = ",")

#inserting all the (c) files
data_c1 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/c/c.pgm", skip = 3, sep = ",")
data_c2 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/c/c2.pgm", skip = 3, sep = ",")
data_c3 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/c/c3.pgm", skip = 3, sep = ",")
data_c4 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/c/c4.pgm", skip = 3, sep = ",")
data_c5 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/c/c5.pgm", skip = 3, sep = ",")
data_c6 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/c/c6.pgm", skip = 3, sep = ",")
data_c7 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/c/c7.pgm", skip = 3, sep = ",")
data_c8 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/c/c8.pgm", skip = 3, sep = ",")

#inserting all the (d) files
data_d1 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/d/d.pgm", skip = 3, sep = ",")
data_d2 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/d/d2.pgm", skip = 3, sep = ",")
data_d3 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/d/d3.pgm", skip = 3, sep = ",")
data_d4 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/d/d4.pgm", skip = 3, sep = ",")
data_d5 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/d/d5.pgm", skip = 3, sep = ",")
data_d6 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/d/d6.pgm", skip = 3, sep = ",")
data_d7 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/d/d7.pgm", skip = 3, sep = ",")
data_d8 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/d/d8.pgm", skip = 3, sep = ",")
#inserting all the (e) files
data_e1 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/e/e.pgm", skip = 3, sep = ",")
data_e2 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/e/e2.pgm", skip = 3, sep = ",")
data_e3 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/e/e3.pgm", skip = 3, sep = ",")
data_e4 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/e/e4.pgm", skip = 3, sep = ",")
data_e5 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/e/e5.pgm", skip = 3, sep = ",")
data_e6 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/e/e6.pgm", skip = 3, sep = ",")
data_e7 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/e/e7.pgm", skip = 3, sep = ",")
data_e8 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/e/e8.pgm", skip = 3, sep = ",")

#inserting all the (f) files
data_f1 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/f/f.pgm", skip = 3, sep = ",")
data_f2 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/f/f2.pgm", skip = 3, sep = ",")
data_f3 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/f/f3.pgm", skip = 3, sep = ",")
data_f4 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/f/f4.pgm", skip = 3, sep = ",")
data_f5 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/f/f5.pgm", skip = 3, sep = ",")
data_f6 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/f/f6.pgm", skip = 3, sep = ",")
data_f7 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/f/f7.pgm", skip = 3, sep = ",")
data_f8 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/f/f8.pgm", skip = 3, sep = ",")

#inserting all the (g) files
data_g1 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/g/g.pgm", skip = 3, sep = ",")
data_g2 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/g/g2.pgm", skip = 3, sep = ",")
data_g3 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/g/g3.pgm", skip = 3, sep = ",")
data_g4 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/g/g4.pgm", skip = 3, sep = ",")
data_g5 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/g/g5.pgm", skip = 3, sep = ",")
data_g6 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/g/g6.pgm", skip = 3, sep = ",")
data_g7 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/g/g7.pgm", skip = 3, sep = ",")
data_g8 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/g/g8.pgm", skip = 3, sep = ",")

#inserting all the (h) files
data_h1 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/h/h.pgm", skip = 3, sep = ",")
data_h2 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/h/h2.pgm", skip = 3, sep = ",")
data_h3 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/h/h3.pgm", skip = 3, sep = ",")
data_h4 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/h/h4.pgm", skip = 3, sep = ",")
data_h5 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/h/h5.pgm", skip = 3, sep = ",")
data_h6 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/h/h6.pgm", skip = 3, sep = ",")
data_h7 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/h/h7.pgm", skip = 3, sep = ",")
data_h8 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/h/h8.pgm", skip = 3, sep = ",")

#inserting all the (i) files
data_i1 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/i/i.pgm", skip = 3, sep = ",")
data_i2 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/i/i2.pgm", skip = 3, sep = ",")
data_i3 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/i/i3.pgm", skip = 3, sep = ",")
data_i4 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/i/i4.pgm", skip = 3, sep = ",")
data_i5 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/i/i5.pgm", skip = 3, sep = ",")
data_i6 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/i/i6.pgm", skip = 3, sep = ",")
data_i7 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/i/i7.pgm", skip = 3, sep = ",")
data_i8 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/i/i8.pgm", skip = 3, sep = ",")

#inserting all the (j) files
data_j1 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/j/j.pgm", skip = 3, sep = ",")
data_j2 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/j/j2.pgm", skip = 3, sep = ",")
data_j3 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/j/j3.pgm", skip = 3, sep = ",")
data_j4 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/j/j4.pgm", skip = 3, sep = ",")
data_j5 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/j/j5.pgm", skip = 3, sep = ",")
data_j6 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/j/j6.pgm", skip = 3, sep = ",")
data_j7 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/j/j7.pgm", skip = 3, sep = ",")
data_j8 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/j/j8.pgm", skip = 3, sep = ",")

# inserting in all the exclamation mark images
data_exm1 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/exclamationMark/exclamationMark.pgm", skip = 3, sep = ",")
data_exm2 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/exclamationMark/exclamationMark2.pgm", skip = 3, sep = ",")
data_exm3 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/exclamationMark/exclamationMark3.pgm", skip = 3, sep = ",")
data_exm4 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/exclamationMark/exclamationMark4.pgm", skip = 3, sep = ",")
data_exm5 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/exclamationMark/exclamationMark5.pgm", skip = 3, sep = ",")
data_exm6 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/exclamationMark/exclamationMark6.pgm", skip = 3, sep = ",")
data_exm7 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/exclamationMark/exclamationMark7.pgm", skip = 3, sep = ",")
data_exm8 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/exclamationMark/exclamationMark8.pgm", skip = 3, sep = ",")
data_exm9 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/exclamationMark/exclamationMark9.pgm", skip = 3, sep = ",")
data_exm10 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/exclamationMark/exclamationMark10.pgm", skip = 3, sep = ",")
data_exm11 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/exclamationMark/exclamationMark11.pgm", skip = 3, sep = ",")
data_exm12 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/exclamationMark/exclamationMark12.pgm", skip = 3, sep = ",")
data_exm13 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/exclamationMark/exclamationMark13.pgm", skip = 3, sep = ",")
data_exm14 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/exclamationMark/exclamationMark14.pgm", skip = 3, sep = ",")
data_exm15 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/exclamationMark/exclamationMark15.pgm", skip = 3, sep = ",")
data_exm16 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/exclamationMark/exclamationMark16.pgm", skip = 3, sep = ",")
data_exm17 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/exclamationMark/exclamationMark17.pgm", skip = 3, sep = ",")
data_exm18 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/exclamationMark/exclamationMark18.pgm", skip = 3, sep = ",")
data_exm19 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/exclamationMark/exclamationMark19.pgm", skip = 3, sep = ",")
data_exm20 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/exclamationMark/exclamationMark20.pgm", skip = 3, sep = ",")

#inserting all of the sad face images 
data_sf1 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/SadFace/sadFace.pgm", skip = 3, sep = ",")
data_sf2 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/SadFace/sadFace2.pgm", skip = 3, sep = ",")
data_sf3 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/SadFace/sadFace3.pgm", skip = 3, sep = ",")
data_sf4 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/SadFace/sadFace4.pgm", skip = 3, sep = ",")
data_sf5 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/SadFace/sadFace5.pgm", skip = 3, sep = ",")
data_sf6 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/SadFace/sadFace6.pgm", skip = 3, sep = ",")
data_sf7 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/SadFace/sadFace7.pgm", skip = 3, sep = ",")
data_sf8 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/SadFace/sadFace8.pgm", skip = 3, sep = ",")
data_sf9 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/sadFace/sadFace9.pgm", skip = 3, sep = ",")
data_sf10 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/sadFace/sadFace10.pgm", skip = 3, sep = ",")
data_sf11 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/sadFace/sadFace11.pgm", skip = 3, sep = ",")
data_sf12 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/sadFace/sadFace12.pgm", skip = 3, sep = ",")
data_sf13 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/sadFace/sadFace13.pgm", skip = 3, sep = ",")
data_sf14 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/sadFace/sadFace14.pgm", skip = 3, sep = ",")
data_sf15 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/sadFace/sadFace15.pgm", skip = 3, sep = ",")
data_sf16 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/sadFace/sadFace16.pgm", skip = 3, sep = ",")
data_sf17 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/sadFace/sadFace17.pgm", skip = 3, sep = ",")
data_sf18 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/sadFace/sadFace18.pgm", skip = 3, sep = ",")
data_sf19 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/sadFace/sadFace19.pgm", skip = 3, sep = ",")
data_sf20 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/sadFace/sadFace20.pgm", skip = 3, sep = ",")

#inserting the smiley face images
data_smf1 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/smileyFace/smileyFace.pgm", skip = 3, sep = ",")
data_smf2 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/smileyFace/smileyFace2.pgm", skip = 3, sep = ",")
data_smf3 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/smileyFace/smileyFace3.pgm", skip = 3, sep = ",")
data_smf4 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/smileyFace/smileyFace4.pgm", skip = 3, sep = ",")
data_smf5 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/smileyFace/smileyFace5.pgm", skip = 3, sep = ",")
data_smf6 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/smileyFace/smileyFace6.pgm", skip = 3, sep = ",")
data_smf7 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/smileyFace/smileyFace7.pgm", skip = 3, sep = ",")
data_smf8 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/smileyFace/smileyFace8.pgm", skip = 3, sep = ",")
data_smf9 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/smileyFace/smileyFace9.pgm", skip = 3, sep = ",")
data_smf10 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/smileyFace/smileyFace10.pgm", skip = 3, sep = ",")
data_smf11 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/smileyFace/smileyFace11.pgm", skip = 3, sep = ",")
data_smf12 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/smileyFace/smileyFace12.pgm", skip = 3, sep = ",")
data_smf13 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/smileyFace/smileyFace13.pgm", skip = 3, sep = ",")
data_smf14 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/smileyFace/smileyFace14.pgm", skip = 3, sep = ",")
data_smf15 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/smileyFace/smileyFace15.pgm", skip = 3, sep = ",")
data_smf16 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/smileyFace/smileyFace16.pgm", skip = 3, sep = ",")
data_smf17 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/smileyFace/smileyFace17.pgm", skip = 3, sep = ",")
data_smf18 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/smileyFace/smileyFace18.pgm", skip = 3, sep = ",")
data_smf19 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/smileyFace/smileyFace19.pgm", skip = 3, sep = ",")
data_smf20 <- read.csv("C:/Users/corma/OneDrive/Desktop/Artificial\ Intelligience/pgm_images/smileyFace/smileyFace20.pgm", skip = 3, sep = ",")

#function to change black squares = 1 and white squares to 0
checkSquares <- function(data)
{
  image_matrix <- matrix(data.matrix(data),  byrow = TRUE, nrow = 18, ncol = 18)
  
  image_matrix < 128
  image_matrix[image_matrix<128] <- 1

  image_matrix >= 128
  image_matrix[image_matrix >= 128] <- 0
  
  return(image_matrix)
}

#making the (a) images matrices
a1_matrix <- checkSquares(data_a1)
a2_matrix <- checkSquares(data_a2)
a3_matrix <- checkSquares(data_a3)
a4_matrix <- checkSquares(data_a4)
a5_matrix <- checkSquares(data_a5)
a6_matrix <- checkSquares(data_a6)
a7_matrix <- checkSquares(data_a7)
a8_matrix <- checkSquares(data_a8)

#making the (b) images matrices
b1_matrix <- checkSquares(data_b1)
b2_matrix <- checkSquares(data_b2)
b3_matrix <- checkSquares(data_b3)
b4_matrix <- checkSquares(data_b4)
b5_matrix <- checkSquares(data_b5)
b6_matrix <- checkSquares(data_b6)
b7_matrix <- checkSquares(data_b7)
b8_matrix <- checkSquares(data_b8)

#making the (c) images matrices
c1_matrix <- checkSquares(data_c1)
c2_matrix <- checkSquares(data_c2)
c3_matrix <- checkSquares(data_c3)
c4_matrix <- checkSquares(data_c4)
c5_matrix <- checkSquares(data_c5)
c6_matrix <- checkSquares(data_c6)
c7_matrix <- checkSquares(data_c7)
c8_matrix <- checkSquares(data_c8)

#making the (d) images matrices
d1_matrix <- checkSquares(data_d1)
d2_matrix <- checkSquares(data_d2)
d3_matrix <- checkSquares(data_d3)
d4_matrix <- checkSquares(data_d4)
d5_matrix <- checkSquares(data_d5)
d6_matrix <- checkSquares(data_d6)
d7_matrix <- checkSquares(data_d7)
d8_matrix <- checkSquares(data_d8)

#making the (e) images matrices
e1_matrix <- checkSquares(data_e1)
e2_matrix <- checkSquares(data_e2)
e3_matrix <- checkSquares(data_e3)
e4_matrix <- checkSquares(data_e4)
e5_matrix <- checkSquares(data_e5)
e6_matrix <- checkSquares(data_e6)
e7_matrix <- checkSquares(data_e7)
e8_matrix <- checkSquares(data_e8)

#making the (f) images matrices
f1_matrix <- checkSquares(data_f1)
f2_matrix <- checkSquares(data_f2)
f3_matrix <- checkSquares(data_f3)
f4_matrix <- checkSquares(data_f4)
f5_matrix <- checkSquares(data_f5)
f6_matrix <- checkSquares(data_f6)
f7_matrix <- checkSquares(data_f7)
f8_matrix <- checkSquares(data_f8)

#making the (g) images matrices
g1_matrix <- checkSquares(data_g1)
g2_matrix <- checkSquares(data_g2)
g3_matrix <- checkSquares(data_g3)
g4_matrix <- checkSquares(data_g4)
g5_matrix <- checkSquares(data_g5)
g6_matrix <- checkSquares(data_g6)
g7_matrix <- checkSquares(data_g7)
g8_matrix <- checkSquares(data_g8)

#making the (h) images matrices
h1_matrix <- checkSquares(data_h1)
h2_matrix <- checkSquares(data_h2)
h3_matrix <- checkSquares(data_h3)
h4_matrix <- checkSquares(data_h4)
h5_matrix <- checkSquares(data_h5)
h6_matrix <- checkSquares(data_h6)
h7_matrix <- checkSquares(data_h7)
h8_matrix <- checkSquares(data_h8)

#making the (i) images matrices
i1_matrix <- checkSquares(data_i1)
i2_matrix <- checkSquares(data_i2)
i3_matrix <- checkSquares(data_i3)
i4_matrix <- checkSquares(data_i4)
i5_matrix <- checkSquares(data_i5)
i6_matrix <- checkSquares(data_i6)
i7_matrix <- checkSquares(data_i7)
i8_matrix <- checkSquares(data_i8)

#making the (j) images matrices
j1_matrix <- checkSquares(data_j1)
j2_matrix <- checkSquares(data_j2)
j3_matrix <- checkSquares(data_j3)
j4_matrix <- checkSquares(data_j4)
j5_matrix <- checkSquares(data_j5)
j6_matrix <- checkSquares(data_j6)
j7_matrix <- checkSquares(data_j7)
j8_matrix <- checkSquares(data_j8)

#making the (exm) images matrices
exm1_matrix <- checkSquares(data_exm1)
exm2_matrix <- checkSquares(data_exm2)
exm3_matrix <- checkSquares(data_exm3)
exm4_matrix <- checkSquares(data_exm4)
exm5_matrix <- checkSquares(data_exm5)
exm6_matrix <- checkSquares(data_exm6)
exm7_matrix <- checkSquares(data_exm7)
exm8_matrix <- checkSquares(data_exm8)
exm9_matrix <- checkSquares(data_exm9)
exm10_matrix <- checkSquares(data_exm10)
exm11_matrix <- checkSquares(data_exm11)
exm12_matrix <- checkSquares(data_exm12)
exm13_matrix <- checkSquares(data_exm13)
exm14_matrix <- checkSquares(data_exm14)
exm15_matrix <- checkSquares(data_exm15)
exm16_matrix <- checkSquares(data_exm16)
exm17_matrix <- checkSquares(data_exm17)
exm18_matrix <- checkSquares(data_exm18)
exm19_matrix <- checkSquares(data_exm19)
exm20_matrix <- checkSquares(data_exm20)

#making the (sf) images matrices
sf1_matrix <- checkSquares(data_sf1)
sf2_matrix <- checkSquares(data_sf2)
sf3_matrix <- checkSquares(data_sf3)
sf4_matrix <- checkSquares(data_sf4)
sf5_matrix <- checkSquares(data_sf5)
sf6_matrix <- checkSquares(data_sf6)
sf7_matrix <- checkSquares(data_sf7)
sf8_matrix <- checkSquares(data_sf8)
sf9_matrix <- checkSquares(data_sf9)
sf10_matrix <- checkSquares(data_sf10)
sf11_matrix <- checkSquares(data_sf11)
sf12_matrix <- checkSquares(data_sf12)
sf13_matrix <- checkSquares(data_sf13)
sf14_matrix <- checkSquares(data_sf14)
sf15_matrix <- checkSquares(data_sf15)
sf16_matrix <- checkSquares(data_sf16)
sf17_matrix <- checkSquares(data_sf17)
sf18_matrix <- checkSquares(data_sf18)
sf19_matrix <- checkSquares(data_sf19)
sf20_matrix <- checkSquares(data_sf20)

#making the (smf) images matrices
smf1_matrix <- checkSquares(data_smf1)
smf2_matrix <- checkSquares(data_smf2)
smf3_matrix <- checkSquares(data_smf3)
smf4_matrix <- checkSquares(data_smf4)
smf5_matrix <- checkSquares(data_smf5)
smf6_matrix <- checkSquares(data_smf6)
smf7_matrix <- checkSquares(data_smf7)
smf8_matrix <- checkSquares(data_smf8)
smf9_matrix <- checkSquares(data_smf9)
smf10_matrix <- checkSquares(data_smf10)
smf11_matrix <- checkSquares(data_smf11)
smf12_matrix <- checkSquares(data_smf12)
smf13_matrix <- checkSquares(data_smf13)
smf14_matrix <- checkSquares(data_smf14)
smf15_matrix <- checkSquares(data_smf15)
smf16_matrix <- checkSquares(data_smf16)
smf17_matrix <- checkSquares(data_smf17)
smf18_matrix <- checkSquares(data_smf18)
smf19_matrix <- checkSquares(data_smf19)
smf20_matrix <- checkSquares(data_smf20)

